# Generated by Django 3.1.7 on 2021-03-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='processing',
        ),
    ]
