# Generated by Django 3.1.7 on 2021-03-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0002_auto_20210323_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='processing',
            new_name='Hotel',
        ),
    ]
