# Generated by Django 3.1.7 on 2021-03-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlp_proj', '0003_auto_20210323_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15)),
                ('file', models.FileField(upload_to='rawdata')),
            ],
        ),
    ]
